### ISSUE TITLE
Make it Full Screen

### ISSUE THREAD

**Issue by sureshssk** [tarun0/ZXing-Standalone-library#1]
Intent intent = new Intent(getApplicationContext(),CaptureActivity.class);
                    getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                            WindowManager.LayoutParams.FLAG_FULLSCREEN);
                    intent.setAction("com.google.zxing.client.android.SCAN");
                    intent.putExtra("SAVE_HISTORY", false);
                    startActivityForResult(intent, 0);

i need to use this barcode scanner in fullscreen 
need to hide share ,history and menu is it possible?
Help me to figure out.

Thanks

**Comment by tarun0** [comment]
Hello @sureshssk ,

The library doesn't support that by default because the purpose is to provide a library with minimal modifications in the original code.

However, to make the scanner in fullscreen, you'll need to make a few modifications (as stated below) to the library and will have to [add it manually](http://stackoverflow.com/a/38423626/2922480). 

- Disable menu in the [`CaptureActivity`](https://github.com/tarun0/ZXing-Standalone-library/blob/master/zxing_standalone/src/main/java/com/google/zxing/client/android/CaptureActivity.java) by returning `false` in the `onCreateOptionsMenu()`, _i.e._ replace the original code with the blow-stated one:
```
@Override
  public boolean onCreateOptionsMenu(Menu menu) {
    return false;
  }
```

- Then add the below two items in the [`CaptureTheme`](https://github.com/tarun0/ZXing-Standalone-library/blob/master/zxing_standalone/src/main/res/values/themes.xml):

1. `<item name="android:windowFullscreen">true</item>`
2.  `<item name="android:windowNoTitle">true</item>`

_i.e._ Replace the style (CaptureTheme) with this code:
```
<style name="CaptureTheme" parent="android:Theme.Holo">
    <item name="android:windowFullscreen">true</item>
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:windowActionBarOverlay">true</item>
    <item name="android:windowActionModeOverlay">true</item>
  </style>
``` 
This removes the `Title`, `Menu` and `Status Bar` making the scanner activity fullscreen.  

Let me know if that solves your issue so that I may close it.

**Comment by sureshssk** [comment]
is it possible to use in portrait mode ?
and remove that box while scanning?

**Comment by tarun0** [comment]
Yes, you can use it in portrait mode by setting the screenOrientation of CaptureActivity in the manifest file.
To remove the box, change the size of the surfaceViewHolder in the CaptureActivity's xml file. However, to capture a bigger sized image, you can use the [`SCAN_WIDTH` and `SCAN_HEIGHT`](https://github.com/tarun0/ZXing-Standalone-library/blob/master/zxing_standalone/src/main/java/com/google/zxing/client/android/Intents.java#L104) extras sent to the captureActivity.
